version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_DATABASE: shop
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-mariadb.sql:/docker-entrypoint-initdb.d/init-mariadb.sql:ro
volumes:
  mariadb_data:
    driver: local
